title: Jordan Patterson
#logo: Gozzoli_Cappella_dei_Magi.jpg
#description: Detail from the fresco by Benozzo Gozzoli, in the "Cappella dei Magi", at Palazzo Medici Riccardi in Florence, Italy. Courtesy of Wikimedia Commons.
#show_downloads: true
theme: jekyll-theme-minimal
